name: Automatic Testing for Booklah App

on:
  push:
    branches:
      - CI/CDdanial
    
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code from GitHub Repo
        uses: actions/checkout@v3
      
      - name: Setup Node.js in Ubuntu
        uses: actions/setup-node@v3
        with:
          node-version: 18
          
      - name: Install dependencies for based on package.json
        run: npm install
        
      - name: Run tests in "tests" folder
        run: npm test
