name: Automatic Testing for BookLah Web App

on:
  push:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout code from GitHub Repo
        uses: actions/checkout@v3
      - name: Setup Node.js in Ubuntu
        uses: actions/setup-node@v3
        with:
          node-version: 18.X
      - name: Remove existing node_modules folder from cloned project
        run: rm -rf /home/runner/work/BookLah/BookLah/node_modules/*
      - name: Install dependencies based on package.json
        run: npm install
      - name: Check Chrome and ChromeDriver versions
        run: |
          google-chrome --version
          chromedriver --version

      - name: Run tests in "tests" folder
        run: npm test
